version: "3.7"
services:
  app:
    build:
      args:
        user: do_an
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: do_an
    container_name: do_an-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - do_an

  db:
    image: mysql:5.7
    container_name: do_an-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 33060:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - do_an

  nginx:
    image: nginx:alpine
    container_name: do_an-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - do_an

networks:
  do_an:
    driver: bridge
